# Generated by Django 3.2 on 2021-05-14 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Leaders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=20, verbose_name='Имя')),
                ('lastname', models.CharField(max_length=20, verbose_name='Фамилия')),
                ('midname', models.CharField(max_length=20, verbose_name='Отчество')),
                ('position', models.CharField(max_length=50, verbose_name='Должность')),
                ('body', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='', verbose_name='Фотография')),
            ],
            options={
                'verbose_name': 'Начальство',
                'verbose_name_plural': 'Начальство',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('body', models.TextField(verbose_name='Текст')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Картинка')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Новости',
                'verbose_name_plural': 'Новости',
            },
        ),
        migrations.CreateModel(
            name='Partners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название Компании')),
                ('link', models.CharField(max_length=255, verbose_name='Ссылка на их сайт')),
            ],
            options={
                'verbose_name': 'Партнеры',
                'verbose_name_plural': 'Партнеры',
            },
        ),
        migrations.CreateModel(
            name='Rates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('title1', models.CharField(default='Бензин Аи-80 (безналичный расчет)', max_length=50, verbose_name='Бензин Аи-80 (безналичный расчет)')),
                ('price1', models.IntegerField(verbose_name='Цена')),
                ('title2', models.CharField(default='Дизельное топливо (безналичный расчет)', max_length=50, verbose_name='ДТ (безналичный расчет)')),
                ('price2', models.IntegerField(verbose_name='Цена')),
                ('title3', models.CharField(default='Дизельное топливо (наличный расчет)', max_length=50, verbose_name='ДТ (наличный расчет)')),
                ('price3', models.IntegerField(verbose_name='Цена')),
                ('title4', models.CharField(default='Мазут (Джалал-Абад) (наличный расчет)', max_length=50, verbose_name='Мазут (наличный расчет)')),
                ('price4', models.IntegerField(verbose_name='Цена')),
                ('title5', models.CharField(default='Мазут (Джалал-Абад) (безналичный расчет)', max_length=50, verbose_name='Мазут (безналичный расчет)')),
                ('price5', models.IntegerField(verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Цены',
                'verbose_name_plural': 'Цены',
            },
        ),
        migrations.CreateModel(
            name='Slides',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Название')),
                ('body', models.CharField(max_length=35, verbose_name='Описание')),
                ('image', models.ImageField(upload_to='', verbose_name='Картинка')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Слайды',
                'verbose_name_plural': 'Слайды',
            },
        ),
        migrations.CreateModel(
            name='Tables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название таблицы')),
                ('params', models.CharField(max_length=255, verbose_name='Наименование параметров')),
                ('norms', models.CharField(max_length=255, verbose_name='Нормы для нефти')),
                ('method', models.CharField(max_length=255, verbose_name='Метод испытания')),
                ('note', models.CharField(max_length=255, verbose_name='Примечание')),
            ],
            options={
                'verbose_name': 'Требования норм',
                'verbose_name_plural': 'Требования норм',
            },
        ),
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('position', models.CharField(max_length=255, verbose_name='Должность')),
                ('text', models.TextField(verbose_name='Текст')),
                ('image', models.ImageField(upload_to='', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Отзывы',
                'verbose_name_plural': 'Отзывы',
            },
        ),
    ]
