# Generated by Django 3.2 on 2021-05-21 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rates',
            name='ai_80',
        ),
        migrations.RemoveField(
            model_name='rates',
            name='ai_price1',
        ),
        migrations.RemoveField(
            model_name='rates',
            name='ai_price2',
        ),
        migrations.RemoveField(
            model_name='rates',
            name='diesel1',
        ),
        migrations.RemoveField(
            model_name='rates',
            name='diesel1_price1',
        ),
        migrations.RemoveField(
            model_name='rates',
            name='diesel1_price2',
        ),
        migrations.RemoveField(
            model_name='rates',
            name='diesel2',
        ),
        migrations.RemoveField(
            model_name='rates',
            name='diesel2_price1',
        ),
        migrations.RemoveField(
            model_name='rates',
            name='diesel2_price2',
        ),
        migrations.RemoveField(
            model_name='rates',
            name='form',
        ),
        migrations.RemoveField(
            model_name='rates',
            name='form1',
        ),
        migrations.RemoveField(
            model_name='rates',
            name='form2',
        ),
        migrations.RemoveField(
            model_name='rates',
            name='fuel_oil',
        ),
        migrations.RemoveField(
            model_name='rates',
            name='tax',
        ),
        migrations.RemoveField(
            model_name='rates',
            name='tax1',
        ),
        migrations.RemoveField(
            model_name='rates',
            name='tax2',
        ),
        migrations.RemoveField(
            model_name='tables',
            name='method',
        ),
        migrations.RemoveField(
            model_name='tables',
            name='norms',
        ),
        migrations.RemoveField(
            model_name='tables',
            name='note',
        ),
        migrations.RemoveField(
            model_name='tables',
            name='num',
        ),
        migrations.RemoveField(
            model_name='tables',
            name='params',
        ),
        migrations.AddField(
            model_name='rates',
            name='diesel_price1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Цена ДТ нал'),
        ),
        migrations.AddField(
            model_name='rates',
            name='diesel_price2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Цена ДТ безнал'),
        ),
        migrations.AddField(
            model_name='rates',
            name='diesel_price3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Цена ДТ с темп. застывания нал'),
        ),
        migrations.AddField(
            model_name='rates',
            name='diesel_price4',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Цена ДТ с темп. застывания безнал'),
        ),
        migrations.AddField(
            model_name='rates',
            name='price1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Цена аи-80 нал'),
        ),
        migrations.AddField(
            model_name='rates',
            name='price2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Цена аи-80 безнал'),
        ),
        migrations.AlterField(
            model_name='rates',
            name='fuel_price1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Цена Мазута нал'),
        ),
        migrations.AlterField(
            model_name='rates',
            name='fuel_price2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Цена Мазута безнал'),
        ),
    ]
