# Generated by Django 3.2 on 2021-05-05 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leaders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=20, verbose_name='Имя')),
                ('lastname', models.CharField(max_length=20, verbose_name='Фамилия')),
                ('midname', models.CharField(max_length=20, verbose_name='Отчество')),
                ('position', models.CharField(max_length=50, verbose_name='Должность')),
                ('body', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='', verbose_name='Фотография')),
            ],
            options={
                'verbose_name': 'Начальство',
                'verbose_name_plural': 'Начальство',
            },
        ),
        migrations.CreateModel(
            name='Rates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('title1', models.CharField(default='Бензин Аи-80 (безналичный расчет)', max_length=50, verbose_name='Бензин Аи-80 (безналичный расчет)')),
                ('price1', models.IntegerField(verbose_name='Цена')),
                ('title2', models.CharField(default='Дизельное топливо (безналичный расчет)', max_length=50, verbose_name='ДТ (безналичный расчет)')),
                ('price2', models.IntegerField(verbose_name='Цена')),
                ('title3', models.CharField(default='Дизельное топливо (наличный расчет)', max_length=50, verbose_name='ДТ (наличный расчет)')),
                ('price3', models.IntegerField(verbose_name='Цена')),
                ('title4', models.CharField(default='Мазут (Джалал-Абад) (наличный расчет)', max_length=50, verbose_name='Мазут (наличный расчет)')),
                ('price4', models.IntegerField(verbose_name='Цена')),
                ('title5', models.CharField(default='Мазут (Джалал-Абад) (безналичный расчет)', max_length=50, verbose_name='Мазут (безналичный расчет)')),
                ('price5', models.IntegerField(verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Цены',
                'verbose_name_plural': 'Цены',
            },
        ),
        migrations.CreateModel(
            name='Tables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название Таблицы')),
            ],
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'Новости', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AddField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
