# Generated by Django 3.2 on 2021-05-17 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rates',
            old_name='diesel1_price1',
            new_name='diesel_price1',
        ),
        migrations.RenameField(
            model_name='rates',
            old_name='diesel1_price2',
            new_name='diesel_price2',
        ),
        migrations.RenameField(
            model_name='rates',
            old_name='diesel2_price1',
            new_name='diesel_price3',
        ),
        migrations.RenameField(
            model_name='rates',
            old_name='diesel2_price2',
            new_name='diesel_price4',
        ),
        migrations.RenameField(
            model_name='rates',
            old_name='ai_price1',
            new_name='price1',
        ),
        migrations.RenameField(
            model_name='rates',
            old_name='ai_price2',
            new_name='price2',
        ),
        migrations.RemoveField(
            model_name='rates',
            name='ai_80',
        ),
        migrations.RemoveField(
            model_name='rates',
            name='diesel1',
        ),
        migrations.RemoveField(
            model_name='rates',
            name='diesel2',
        ),
        migrations.RemoveField(
            model_name='rates',
            name='form',
        ),
        migrations.RemoveField(
            model_name='rates',
            name='fuel_oil',
        ),
        migrations.RemoveField(
            model_name='rates',
            name='tax',
        ),
    ]
