# Generated by Django 3.2 on 2021-04-28 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('title1', models.CharField(default='Бензин Аи-80(безналичный расчет)', max_length=50, verbose_name='Бензин Аи-80(безналичный расчет)')),
                ('price_80', models.IntegerField(verbose_name='Цена')),
                ('title2', models.CharField(default='Дизельное топливо (безналичный расчет)', max_length=50, verbose_name='ДТ (безналичный расчет)')),
                ('price_dt_card', models.IntegerField(verbose_name='Цена')),
                ('title3', models.CharField(default='Дизельное топливо (наличный расчет)', max_length=50, verbose_name='ДТ(наличный расчет)')),
                ('price_dt_cash', models.IntegerField(verbose_name='Цена')),
                ('title4', models.CharField(default='Мазут (Джалал-Абад) (наличный расчет)', max_length=50, verbose_name='Мазут(наличный расчет)')),
                ('price_mazut_cash', models.IntegerField(verbose_name='Цена')),
                ('title5', models.CharField(default='Мазут (Джалал-Абад) (безналичный расчет)', max_length=50, verbose_name='Мазут(безналичный расчет)')),
                ('price_mazut_card', models.IntegerField(verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Цены',
                'verbose_name_plural': 'Цены',
            },
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'Новости', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AddField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
