# Generated by Django 3.2 on 2021-05-14 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tables',
            name='num',
            field=models.IntegerField(null=True, verbose_name='№'),
        ),
    ]
