# Generated by Django 3.2 on 2021-05-23 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_auto_20210521_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='plans',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Картинка'),
        ),
        migrations.AddField(
            model_name='progress',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Картинка'),
        ),
        migrations.CreateModel(
            name='ProgressImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='images/progress/')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.progress')),
            ],
        ),
        migrations.CreateModel(
            name='PlansImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='images/plans/')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.plans')),
            ],
        ),
        migrations.CreateModel(
            name='NewsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='images/news/')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.news')),
            ],
        ),
    ]
