# Generated by Django 3.2 on 2021-05-14 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_tables_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tables',
            name='num',
            field=models.CharField(max_length=255, null=True, verbose_name='№'),
        ),
    ]
