# Generated by Django 3.2 on 2021-05-17 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_auto_20210517_1817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rates',
            name='form1',
        ),
        migrations.RemoveField(
            model_name='rates',
            name='form2',
        ),
        migrations.RemoveField(
            model_name='rates',
            name='tax1',
        ),
        migrations.RemoveField(
            model_name='rates',
            name='tax2',
        ),
    ]
