# Generated by Django 3.2 on 2021-04-28 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_auto_20210428_1905'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rates',
            old_name='price_80',
            new_name='price1',
        ),
        migrations.RenameField(
            model_name='rates',
            old_name='price_dt_card',
            new_name='price2',
        ),
        migrations.RenameField(
            model_name='rates',
            old_name='price_dt_cash',
            new_name='price3',
        ),
        migrations.RenameField(
            model_name='rates',
            old_name='price_mazut_card',
            new_name='price4',
        ),
        migrations.RenameField(
            model_name='rates',
            old_name='price_mazut_cash',
            new_name='price5',
        ),
    ]
