# Generated by Django 3.2 on 2021-05-17 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_auto_20210517_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rates',
            name='diesel_price1',
            field=models.IntegerField(blank=True, null=True, verbose_name='Цена ДТ нал'),
        ),
        migrations.AlterField(
            model_name='rates',
            name='diesel_price2',
            field=models.IntegerField(blank=True, null=True, verbose_name='Цена ДТ безнал'),
        ),
        migrations.AlterField(
            model_name='rates',
            name='diesel_price3',
            field=models.IntegerField(blank=True, null=True, verbose_name='Цена ДТ с темп. застывания нал'),
        ),
        migrations.AlterField(
            model_name='rates',
            name='diesel_price4',
            field=models.IntegerField(blank=True, null=True, verbose_name='Цена ДТ с темп. застывания безнал'),
        ),
        migrations.AlterField(
            model_name='rates',
            name='fuel_price1',
            field=models.IntegerField(blank=True, null=True, verbose_name='Цена Мазута нал'),
        ),
        migrations.AlterField(
            model_name='rates',
            name='fuel_price2',
            field=models.IntegerField(blank=True, null=True, verbose_name='Цена Мазута безнал'),
        ),
        migrations.AlterField(
            model_name='rates',
            name='price1',
            field=models.IntegerField(blank=True, null=True, verbose_name='Цена аи-80 нал'),
        ),
        migrations.AlterField(
            model_name='rates',
            name='price2',
            field=models.IntegerField(blank=True, null=True, verbose_name='Цена аи-80 безнал'),
        ),
    ]
