# Generated by Django 3.2 on 2021-05-23 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_auto_20210523_1753'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plansimage',
            old_name='news',
            new_name='plans',
        ),
        migrations.RenameField(
            model_name='progressimage',
            old_name='news',
            new_name='progress',
        ),
    ]
